### ISSUE TITLE
Resume link

### ISSUE THREAD

**Issue by Lukeghenco** [learn-co-curriculum/careers-building-your-resume#1]
The resume link is showing up as a presentation instead of a document. It is very difficult to edit the file in this format.

**Comment by AnnJohn** [comment]
thanks @Lukeghenco. We'll update this within the next 24 hours to make it a Google Word doc. Sorry about the issue for now.

**Comment by Lukeghenco** [comment]
Thanks AnnJohn,

  I went ahead and converted it to a document.

**Comment by AnnJohn** [comment]
thanks @Lukeghenco, and if you have any feedback on this curriculum (we have a few final units to deploy soon), please let us know. You can always raise issues or slack me directly in the Learn slack org!

**Comment by Lukeghenco** [comment]
Ok,

I saw that I was part of the ‘g-416’ github team. Is that more lessons I need to be going through? I have just been working on the list that Jackie sent me.

**Comment by AnnJohn** [comment]
yes, the g-416 has additional lessons than the ones Jackie sent over. She sent over the first three units, and there are three additional units that have been added to the g-416 track. We'll be finalizing and adding the rest of the content by the end of this week, but in the meantime, the lessons provided should take a bit of time to go through.

**Comment by Lukeghenco** [comment]
Yea, just trying to figure out the order of the other lessons, in the g-416 track. I am on the last section of the content Jackie sent me.

**Comment by AnnJohn** [comment]
there should be three units following what Jackie sent over (assuming still that the last lessons from her are on resumes) that address networking and interviewing. It looks like you're in the track, but here's the invite again just in case- https://learn.co/join/340122b55f1bfe37

But your current default track might be set to the full stack track so to switch tracks, you can go to learn.co/tracks and switch to the Career Prep track.

**Comment by Sdcrouse** [comment]
I think all of this has been fixed.
